wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706018647.246284
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.13
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
